[package]
name = "win32_notif"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
windows = { version = "0.58.0", features = [
  "Win32_UI_Notifications",
  "Data_Xml_Dom",
  "UI_Notifications",
  "Foundation_Collections",
] }

[features]
default = []
unsafe = []
