[package]
name = "win32_notif"
version = "0.3.0"
edition = "2021"
description = "Wrapper around Windows UWP XAML (WinRT) Notification api"
license = "MIT"
repository = "https://github.com/AHQ-Softwares/win32_notif"
authors = ["AHQ Softwares", "AHQ <ahqsecret@gmail.com>"]
documentation = "https://ahq-softwares.github.io/win32_notif/"

[package.metadata.docs.rs]
all-features = true

[dependencies]
windows = { version = "0.58.0", features = [
  "Win32_UI_Notifications",
  "Data_Xml_Dom",
  "UI_Notifications",
  "Foundation_Collections",
] }

[features]
default = ["unsafe"]
unsafe = []
