name: Publish to cargo

on:
  push:
    branches:
      - master
    paths:
      - Cargo.toml

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
